/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface KortxyzAggrid {}
  interface KortxyzApp {
    'source': string;
  }
  interface KortxyzCode {
    'layer': any;
    'left': number;
    'top': number;
  }
  interface KortxyzContextmenu {
    'left': number;
    'top': number;
  }
  interface KortxyzDialog {
    'left': number;
    'top': number;
  }
  interface KortxyzFooter {
    /**
    * Handles if the GPS should be turn off or on
    */
    'gpsState': string;
  }
  interface KortxyzLayergroup {}
  interface KortxyzLayeritem {
    'active': boolean;
    'name': string;
  }
  interface KortxyzLayerlist {
    'handleFile': (e: any) => Promise<void>;
    'sourcesURL': any;
  }
  interface KortxyzLayermenu {
    'left': number;
    'top': number;
  }
  interface KortxyzLeaflet {
    'geojson': any;
    'map': any;
  }
  interface KortxyzMapbox {
    'accesstoken': string;
    'addLayer': (name: any, source: any) => Promise<void>;
    'map': mapboxgl.Map;
    'mapstyle': any;
  }
  interface KortxyzSidebar {}
  interface KortxyzSideitem {
    'icon': string;
    'name': string;
    'small': boolean;
    'width': Number;
  }
  interface KortxyzSourceitem {
    'active': boolean;
    'name': string;
  }
  interface KortxyzSourcelist {
    'handleFile': (e: any) => Promise<void>;
  }
}

declare global {


  interface HTMLKortxyzAggridElement extends Components.KortxyzAggrid, HTMLStencilElement {}
  var HTMLKortxyzAggridElement: {
    prototype: HTMLKortxyzAggridElement;
    new (): HTMLKortxyzAggridElement;
  };

  interface HTMLKortxyzAppElement extends Components.KortxyzApp, HTMLStencilElement {}
  var HTMLKortxyzAppElement: {
    prototype: HTMLKortxyzAppElement;
    new (): HTMLKortxyzAppElement;
  };

  interface HTMLKortxyzCodeElement extends Components.KortxyzCode, HTMLStencilElement {}
  var HTMLKortxyzCodeElement: {
    prototype: HTMLKortxyzCodeElement;
    new (): HTMLKortxyzCodeElement;
  };

  interface HTMLKortxyzContextmenuElement extends Components.KortxyzContextmenu, HTMLStencilElement {}
  var HTMLKortxyzContextmenuElement: {
    prototype: HTMLKortxyzContextmenuElement;
    new (): HTMLKortxyzContextmenuElement;
  };

  interface HTMLKortxyzDialogElement extends Components.KortxyzDialog, HTMLStencilElement {}
  var HTMLKortxyzDialogElement: {
    prototype: HTMLKortxyzDialogElement;
    new (): HTMLKortxyzDialogElement;
  };

  interface HTMLKortxyzFooterElement extends Components.KortxyzFooter, HTMLStencilElement {}
  var HTMLKortxyzFooterElement: {
    prototype: HTMLKortxyzFooterElement;
    new (): HTMLKortxyzFooterElement;
  };

  interface HTMLKortxyzLayergroupElement extends Components.KortxyzLayergroup, HTMLStencilElement {}
  var HTMLKortxyzLayergroupElement: {
    prototype: HTMLKortxyzLayergroupElement;
    new (): HTMLKortxyzLayergroupElement;
  };

  interface HTMLKortxyzLayeritemElement extends Components.KortxyzLayeritem, HTMLStencilElement {}
  var HTMLKortxyzLayeritemElement: {
    prototype: HTMLKortxyzLayeritemElement;
    new (): HTMLKortxyzLayeritemElement;
  };

  interface HTMLKortxyzLayerlistElement extends Components.KortxyzLayerlist, HTMLStencilElement {}
  var HTMLKortxyzLayerlistElement: {
    prototype: HTMLKortxyzLayerlistElement;
    new (): HTMLKortxyzLayerlistElement;
  };

  interface HTMLKortxyzLayermenuElement extends Components.KortxyzLayermenu, HTMLStencilElement {}
  var HTMLKortxyzLayermenuElement: {
    prototype: HTMLKortxyzLayermenuElement;
    new (): HTMLKortxyzLayermenuElement;
  };

  interface HTMLKortxyzLeafletElement extends Components.KortxyzLeaflet, HTMLStencilElement {}
  var HTMLKortxyzLeafletElement: {
    prototype: HTMLKortxyzLeafletElement;
    new (): HTMLKortxyzLeafletElement;
  };

  interface HTMLKortxyzMapboxElement extends Components.KortxyzMapbox, HTMLStencilElement {}
  var HTMLKortxyzMapboxElement: {
    prototype: HTMLKortxyzMapboxElement;
    new (): HTMLKortxyzMapboxElement;
  };

  interface HTMLKortxyzSidebarElement extends Components.KortxyzSidebar, HTMLStencilElement {}
  var HTMLKortxyzSidebarElement: {
    prototype: HTMLKortxyzSidebarElement;
    new (): HTMLKortxyzSidebarElement;
  };

  interface HTMLKortxyzSideitemElement extends Components.KortxyzSideitem, HTMLStencilElement {}
  var HTMLKortxyzSideitemElement: {
    prototype: HTMLKortxyzSideitemElement;
    new (): HTMLKortxyzSideitemElement;
  };

  interface HTMLKortxyzSourceitemElement extends Components.KortxyzSourceitem, HTMLStencilElement {}
  var HTMLKortxyzSourceitemElement: {
    prototype: HTMLKortxyzSourceitemElement;
    new (): HTMLKortxyzSourceitemElement;
  };

  interface HTMLKortxyzSourcelistElement extends Components.KortxyzSourcelist, HTMLStencilElement {}
  var HTMLKortxyzSourcelistElement: {
    prototype: HTMLKortxyzSourcelistElement;
    new (): HTMLKortxyzSourcelistElement;
  };
  interface HTMLElementTagNameMap {
    'kortxyz-aggrid': HTMLKortxyzAggridElement;
    'kortxyz-app': HTMLKortxyzAppElement;
    'kortxyz-code': HTMLKortxyzCodeElement;
    'kortxyz-contextmenu': HTMLKortxyzContextmenuElement;
    'kortxyz-dialog': HTMLKortxyzDialogElement;
    'kortxyz-footer': HTMLKortxyzFooterElement;
    'kortxyz-layergroup': HTMLKortxyzLayergroupElement;
    'kortxyz-layeritem': HTMLKortxyzLayeritemElement;
    'kortxyz-layerlist': HTMLKortxyzLayerlistElement;
    'kortxyz-layermenu': HTMLKortxyzLayermenuElement;
    'kortxyz-leaflet': HTMLKortxyzLeafletElement;
    'kortxyz-mapbox': HTMLKortxyzMapboxElement;
    'kortxyz-sidebar': HTMLKortxyzSidebarElement;
    'kortxyz-sideitem': HTMLKortxyzSideitemElement;
    'kortxyz-sourceitem': HTMLKortxyzSourceitemElement;
    'kortxyz-sourcelist': HTMLKortxyzSourcelistElement;
  }
}

declare namespace LocalJSX {
  interface KortxyzAggrid extends JSXBase.HTMLAttributes<HTMLKortxyzAggridElement> {}
  interface KortxyzApp extends JSXBase.HTMLAttributes<HTMLKortxyzAppElement> {
    'source'?: string;
  }
  interface KortxyzCode extends JSXBase.HTMLAttributes<HTMLKortxyzCodeElement> {
    'layer'?: any;
    'left'?: number;
    'top'?: number;
  }
  interface KortxyzContextmenu extends JSXBase.HTMLAttributes<HTMLKortxyzContextmenuElement> {
    'left'?: number;
    'top'?: number;
  }
  interface KortxyzDialog extends JSXBase.HTMLAttributes<HTMLKortxyzDialogElement> {
    'left'?: number;
    'top'?: number;
  }
  interface KortxyzFooter extends JSXBase.HTMLAttributes<HTMLKortxyzFooterElement> {
    /**
    * Handles if the GPS should be turn off or on
    */
    'gpsState'?: string;
  }
  interface KortxyzLayergroup extends JSXBase.HTMLAttributes<HTMLKortxyzLayergroupElement> {}
  interface KortxyzLayeritem extends JSXBase.HTMLAttributes<HTMLKortxyzLayeritemElement> {
    'active'?: boolean;
    'name'?: string;
  }
  interface KortxyzLayerlist extends JSXBase.HTMLAttributes<HTMLKortxyzLayerlistElement> {
    'onLayerRemoved'?: (event: CustomEvent<any>) => void;
    'sourcesURL'?: any;
  }
  interface KortxyzLayermenu extends JSXBase.HTMLAttributes<HTMLKortxyzLayermenuElement> {
    'left'?: number;
    'top'?: number;
  }
  interface KortxyzLeaflet extends JSXBase.HTMLAttributes<HTMLKortxyzLeafletElement> {
    'geojson'?: any;
    'map'?: any;
  }
  interface KortxyzMapbox extends JSXBase.HTMLAttributes<HTMLKortxyzMapboxElement> {
    'accesstoken'?: string;
    'map'?: mapboxgl.Map;
    'mapstyle'?: any;
    'onLayerAdded'?: (event: CustomEvent<any>) => void;
    'onLayerRemoved'?: (event: CustomEvent<any>) => void;
    'onMapLoaded'?: (event: CustomEvent<any>) => void;
    'onNewStyle'?: (event: CustomEvent<any>) => void;
    'onSourceAdded'?: (event: CustomEvent<any>) => void;
  }
  interface KortxyzSidebar extends JSXBase.HTMLAttributes<HTMLKortxyzSidebarElement> {}
  interface KortxyzSideitem extends JSXBase.HTMLAttributes<HTMLKortxyzSideitemElement> {
    'icon'?: string;
    'name'?: string;
    'onSidebarResized'?: (event: CustomEvent<any>) => void;
    'small'?: boolean;
    'width'?: Number;
  }
  interface KortxyzSourceitem extends JSXBase.HTMLAttributes<HTMLKortxyzSourceitemElement> {
    'active'?: boolean;
    'name'?: string;
  }
  interface KortxyzSourcelist extends JSXBase.HTMLAttributes<HTMLKortxyzSourcelistElement> {}

  interface IntrinsicElements {
    'kortxyz-aggrid': KortxyzAggrid;
    'kortxyz-app': KortxyzApp;
    'kortxyz-code': KortxyzCode;
    'kortxyz-contextmenu': KortxyzContextmenu;
    'kortxyz-dialog': KortxyzDialog;
    'kortxyz-footer': KortxyzFooter;
    'kortxyz-layergroup': KortxyzLayergroup;
    'kortxyz-layeritem': KortxyzLayeritem;
    'kortxyz-layerlist': KortxyzLayerlist;
    'kortxyz-layermenu': KortxyzLayermenu;
    'kortxyz-leaflet': KortxyzLeaflet;
    'kortxyz-mapbox': KortxyzMapbox;
    'kortxyz-sidebar': KortxyzSidebar;
    'kortxyz-sideitem': KortxyzSideitem;
    'kortxyz-sourceitem': KortxyzSourceitem;
    'kortxyz-sourcelist': KortxyzSourcelist;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


