/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KortxyzMapinfo {
        "lngLat": maplibregl.LngLat;
    }
    interface KortxyzMapinfoContent {
        "template": string;
        "text": string;
        "url": string;
    }
    interface KortxyzMaplibre {
        "center"?: string;
        "cooperativeGestures"?: boolean;
        "getMap": () => Promise<any>;
        "mapboxkey": string;
        "mapstyle"?: maplibregl.StyleSpecification | string;
        "zoom"?: number;
    }
}
export interface KortxyzMapinfoCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKortxyzMapinfoElement;
}
declare global {
    interface HTMLKortxyzMapinfoElement extends Components.KortxyzMapinfo, HTMLStencilElement {
    }
    var HTMLKortxyzMapinfoElement: {
        prototype: HTMLKortxyzMapinfoElement;
        new (): HTMLKortxyzMapinfoElement;
    };
    interface HTMLKortxyzMapinfoContentElement extends Components.KortxyzMapinfoContent, HTMLStencilElement {
    }
    var HTMLKortxyzMapinfoContentElement: {
        prototype: HTMLKortxyzMapinfoContentElement;
        new (): HTMLKortxyzMapinfoContentElement;
    };
    interface HTMLKortxyzMaplibreElement extends Components.KortxyzMaplibre, HTMLStencilElement {
    }
    var HTMLKortxyzMaplibreElement: {
        prototype: HTMLKortxyzMaplibreElement;
        new (): HTMLKortxyzMaplibreElement;
    };
    interface HTMLElementTagNameMap {
        "kortxyz-mapinfo": HTMLKortxyzMapinfoElement;
        "kortxyz-mapinfo-content": HTMLKortxyzMapinfoContentElement;
        "kortxyz-maplibre": HTMLKortxyzMaplibreElement;
    }
}
declare namespace LocalJSX {
    interface KortxyzMapinfo {
        "lngLat"?: maplibregl.LngLat;
        "onNewMarkerPosition"?: (event: KortxyzMapinfoCustomEvent<any>) => void;
    }
    interface KortxyzMapinfoContent {
        "template"?: string;
        "text"?: string;
        "url"?: string;
    }
    interface KortxyzMaplibre {
        "center"?: string;
        "cooperativeGestures"?: boolean;
        "mapboxkey"?: string;
        "mapstyle"?: maplibregl.StyleSpecification | string;
        "zoom"?: number;
    }
    interface IntrinsicElements {
        "kortxyz-mapinfo": KortxyzMapinfo;
        "kortxyz-mapinfo-content": KortxyzMapinfoContent;
        "kortxyz-maplibre": KortxyzMaplibre;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kortxyz-mapinfo": LocalJSX.KortxyzMapinfo & JSXBase.HTMLAttributes<HTMLKortxyzMapinfoElement>;
            "kortxyz-mapinfo-content": LocalJSX.KortxyzMapinfoContent & JSXBase.HTMLAttributes<HTMLKortxyzMapinfoContentElement>;
            "kortxyz-maplibre": LocalJSX.KortxyzMaplibre & JSXBase.HTMLAttributes<HTMLKortxyzMaplibreElement>;
        }
    }
}
